### ISSUE TITLE
UI change experienced in Lab Answer Key Module 1

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#1]
# Module: 01
#### Step: 1b

Description of issue
Step states: 
b. Select the **Hide Script Pane** up-arrow icon to display the console.

New step: The new option is press **CTL + R** to toggle the console pane.

Repro steps:
https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_01_Configuring_Windows_PowerShell_finding_and_running_commands.md#task-2-customize-the-appearance-of-the-ise-to-use-the-single-pane-view-hide-the-command-pane-and-adjust-the-font-size

**Comment by PaulDash** [comment]
Yes, but the up-arrow icon also does this, so step is not incorrect.

**Comment by abUp** [comment]
please somebody could help me instal the  Virtual machines: AZ-040T00A-LON-DC1 and AZ-040T00A-LON-CL1 ?

**Comment by TJGitHubUser** [comment]
Issue resolved.
