### ISSUE TITLE
PowerShell 7 doesn't recognise Az commands. Command fails on Module 9 Ex 3 Task 1 step 4. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#2]
# Module : LAK 09
#### Step: 04

Description of issue

PowerShell 7 doesn't recognise Az commands. Command fails on Ex 3 Task 1 step 4. 
This command executes without issue in PowerShell 5.

PS 7  version information included (screenshot).

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_09_Azure_resource_management_with_PowerShell.md#task-1-create-an-azure-vm-by-using-powershell

![2021-10-08_120216](https://user-images.githubusercontent.com/62302805/136809970-908b8351-6bd1-4be7-8823-7fcac8f1515b.JPG)

![2021-10-08_120142](https://user-images.githubusercontent.com/62302805/136810245-756ffaee-8757-45ad-9d0f-444d7e7c8d70.JPG)

**Comment by erikvani** [comment]
This works:
Install-Module Az.Compute
Connect-AzAccount
$cred = Get-Credential -Message "Enter a username and password for the virtual machine."

**Comment by craigbeeremct** [comment]
Possibly a stupid question, but have you installed the Az modules in PowerShell 7?

If you run "Install-Module Az" in v5, that does not install the modules for v7, and vice versa.

Check `_user_\Documents\PowerShell\Modules` (v7) and `_user_\Documents\WIndowsPowerShell\Modules` (v5). 

Or `c:\program files\powershell\7\modules` and `c:\program files\windowspowershell\modules` if you didn't use "-Scope Currentuser".
