### ISSUE TITLE
Can we distinguish the two "Using PowerShell pipeline" labs please

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#21]
There are two labs called "Lab answer key: Using PowerShell pipeline". Can we get the names changed to distinguish them please. 

The Skillable lab provider only displays the names of the labs, not the numbers, so there is no way to distinguish them.

Either change the titles, or maybe number the second lab's exercises 3 and 4 instead of 1 and 2.

Or (better still) put the lab number inside the lab's markdown.

**Comment by TJGitHubUser** [comment]
Issue resolved.
