### ISSUE TITLE
Update AZ-040T00 with capabilities of PowerShell 7

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#22]
Is it in the roadmap to update AZ-040T00 with capabilities of PowerShell 7 on Linux etc. and remove older Windows PowerShell details?

@sdwheeler, from the PowerShell content team, asked to contact the Learning team.
https://github.com/PowerShell/PowerShell-RFC/issues/330#issuecomment-1248392187

And Kim Spilker, from Learning, asked to submit an issue on GitHub during the Oct 12 [MCT Special Session](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE57aWs).

**Comment by SkillableBB** [comment]
Confirming PowerShell 7 needs to be updated from 7.1 to 7.3. Currently, it fails to recognize Connect-AzAccount cmdlet [p1]. Updating powershell (for newtonsoft.json) or downgrading the az module(s) should address that; alternatively, the other version of PowerShell accessible in the VM will be able to complete the cmdlets instructed in the lab with no issue [p2].

[p1] 

![image](https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/assets/94069201/a692ed0e-096a-49e8-9761-5e38c957546e)

[p2]

![image](https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/assets/94069201/765b9e75-1a51-405e-847c-0198dc3d5d83)

**Comment by v-asamim** [comment]
@Ayanmullick The instructions for the lab have been recently updated.

**Comment by Ayanmullick** [comment]
> @Ayanmullick The instructions for the lab have been recently updated.

Even the updated instruction is using the older version instead of the current version of PowerShell.

[AZ-040T00-Automating-Administration-with-PowerShell (microsoftlearning.github.io)](https://microsoftlearning.github.io/AZ-040T00-Automating-Administration-with-PowerShell/Instructions/Labs/LAB_01_Configuring_Windows_PowerShell_finding_and_running_commands.html#exercise-1-configuring-the-windows-powershell-console-application)

**Comment by TJGitHubUser** [comment]
Closing this issue, resolved.
