### ISSUE TITLE
AzureAD Module and MSOnline Module are deprecated

### ISSUE THREAD

**Issue by PowershellNinja** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#24]
# Module: 10
#### Step: All

The AzureAD, AzureADPreview and MSOnline Modules are deprecated and due to cease working on June 30, 2023:
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/microsoft-entra-change-announcements-september-2022-train/ba-p/2967454#:~:text=for%20Header%20keys.-,Azure%20AD%20Graph%20API,-Azure%20AD%20Graph

Exercise 1 in Lab 10 will need to be updated to use the Microsoft.Graph Module instead of the AzureAd Module, otherwise exercise 1 will cease to work after June 30, 2023.

https://learn.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0

**Comment by v-asamim** [comment]
@PowershellNinja The instructions for the lab have been recently updated.

**Comment by TJGitHubUser** [comment]
Closed as resolved.
