### ISSUE TITLE
PowerShell 7.1 in Lab 9 needs to be updated

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#27]
#### Step: 07

PowerShell 7 needs to be updated from 7.1 to 7.3. Currently, it fails to recognize the Connect-AzAccount cmdlet in step 7 [p1]. Updating powershell (for newtonsoft.json) or downgrading the az module(s) should address that; alternatively, the other version of PowerShell accessible in the VM will be able to complete the cmdlets instructed in the lab with no issue [p2].

[p1]

![259113590-a692ed0e-096a-49e8-9761-5e38c957546e](https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/assets/94069201/1f1ab8db-830c-4696-b6fc-64d57f7f45ea)

[p2]

![259118564-765b9e75-1a51-405e-847c-0198dc3d5d83](https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/assets/94069201/dad13a14-c869-4981-a56e-b52dda4fb08c)

**Comment by v-asamim** [comment]
@SkillableBB The instructions for the lab have been recently updated.

**Comment by SkillableBB** [comment]
Thanks @v-asamim! That took care of it, closing this out. :)

**Comment by peetrike** [comment]
> PowerShell 7 needs to be updated from 7.1 to 7.3.

Current (and LTS) version is 7.4.  Why not this version?
