### ISSUE TITLE
Mod 10 Labs need to be updated from AzureAD module to Microsoft.Graph module

### ISSUE THREAD

**Issue by PurvesG2** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#29]
# Module: 10
#### Step: 03-all

Description of issue
 Task 1 Step 3 	Install-Module AzureAD and all steps in Lab 1
deprecation date for MS Online, AzureAD, and AzureAD Preview PowerShell modules to March 30, 2024.  
Must Install-Module Microsoft.Graph 
All command syntax must be rewritten using the MG commands.

Repro steps: N/A

**Comment by v-asamim** [comment]
@PurvesG2 The instructions for the lab have been recently updated.

**Comment by TJGitHubUser** [comment]
Closed as resolved.
