### ISSUE TITLE
MakeCert is deprecated

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#32]
# Module: 01
#### Step: 09

Description of issue

**MakeCert is deprecated.** https://learn.microsoft.com/en-us/windows/win32/seccrypto/makecert

The lab should make reference to New-SelfSignedCertificate and point out which versions of PowerShell and Windows support each.

Current text:
"Learn about code signing. You should learn that MakeCert.exe is used to create a self-signed digital certificate."

Repro steps:

1.
1.
1.

**Comment by TJGitHubUser** [comment]
Good point, we updated and issue now resolved. Thanks.
