### ISSUE TITLE
Need to enable remoting on the client - the remoting background jobs are currently failing

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#7]
# Module: LAB_AK_11_Using_background_jobs_and_scheduled_jobs
#### Step: 4

Description of issue
You need to inject an instruction here to enable remoting, remember this is a client O/S we are trying to run a remoting session to...

4. Enable-PSRemoting -Force
5. <This will be the old step 4> 

Repro steps:

Because this is asking us to run an invoke command to a client O/S the OS needs to be told to turn on remoting, The current labs are failing because of this. I ran the Enable-PSRemoting -Force command and re-ran the failing commands and it now works.

**Comment by craigbeeremct** [comment]
Enable-PSRemoting is run on CL1 during "Performing remote administration with PowerShell". Is it disabled during a subsequent lab?
