### ISSUE TITLE
Split the Module 3 lab?

### ISSUE THREAD

**Issue by PaulDash** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#8]
# Module: 03
## Lab/Demo: 01

Module 3 has a two-hour lab covering quite a few different topics. The 10961 had four separate labs instead.

Having students practice smaller chunks of knowledge is more conductive to learning. Plus there's more flexibility with timing without having to tell students to do the lab one Exercise at a time. What does everyone here think?

**Comment by craigbeeremct** [comment]
I've just taught it yesterday and this morning. I split it into four bits the same way 10961C used to do. 

Some lecture then exercise 1 on Monday afternoon. On Tuesday morning some lecture then exercise 2, more lecture, exercise 4, lecture, then exercise 3 (I like to finish up with ForEach-Object).

It worked fine.

**Comment by TJGitHubUser** [comment]
Lab has been split into 3A and 3B.
