### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell#9]
In the first five labs, of the answer key side, it states Labs instead of Lab answer key.  Here is the list:

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_01_Configuring_Windows_PowerShell_finding_and_running_commands.md

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_02_Administering_local_systems_using_PowerShell.md

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_03_Working_with_Windows_PowerShell_Pipeline.md

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_04_Using_PSProviders_and_PSDrives.md

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_05_Making_changes_by_using_CIM_and_WMI.md

You can see later, the answer key starts using "Lab Answer Key" as shown in this example:

https://github.com/MicrosoftLearning/AZ-040T00-Automating-Administration-with-PowerShell/blob/master/Instructions/Labs/LAB_AK_07_Windows_PowerShell_Scripting.md

Could we have "Lab Answer Key" added to the first five for consistency please?

Thank you.

**Comment by TJGitHubUser** [comment]
Resolved.
